import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/* THIS FILE IS GENERATED BY ESBUILD. DO NOT EDIT DIRECTLY.
   Source lives at https://github.com/felipeverissimo/Dashsidian */`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
